# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lucky.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Lucky(object):
    def setupUi(self, Lucky):
        Lucky.setObjectName("Lucky")
        Lucky.resize(800, 800)
        Lucky.setMinimumSize(QtCore.QSize(800, 600))
        Lucky.setMaximumSize(QtCore.QSize(800, 800))
        self.centralwidget = QtWidgets.QWidget(Lucky)
        self.centralwidget.setObjectName("centralwidget")
        self.answer_table = QtWidgets.QTableWidget(self.centralwidget)
        self.answer_table.setGeometry(QtCore.QRect(5, 5, 230, 790))
        self.answer_table.setMinimumSize(QtCore.QSize(230, 590))
        self.answer_table.setMaximumSize(QtCore.QSize(230, 790))
        self.answer_table.setObjectName("answer_table")
        self.answer_table.setColumnCount(2)
        self.answer_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("期号")
        item.setBackground(QtGui.QColor(240, 229, 189))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.answer_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.answer_table.setHorizontalHeaderItem(1, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(250, 260, 531, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refresh = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.refresh.setObjectName("refresh")
        self.horizontalLayout.addWidget(self.refresh)
        self.statistics = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.statistics.setObjectName("statistics")
        self.horizontalLayout.addWidget(self.statistics)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 300, 54, 12))
        self.label.setObjectName("label")
        self.result_table = QtWidgets.QTableWidget(self.centralwidget)
        self.result_table.setGeometry(QtCore.QRect(250, 320, 531, 211))
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(5)
        self.result_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(4, item)
        self.lucky = QtWidgets.QPushButton(self.centralwidget)
        self.lucky.setGeometry(QtCore.QRect(260, 550, 511, 23))
        self.lucky.setObjectName("lucky")
        self.result_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.result_edit.setGeometry(QtCore.QRect(250, 590, 531, 201))
        self.result_edit.setObjectName("result_edit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 210, 51, 16))
        self.label_2.setObjectName("label_2")
        self.strategySlider = QtWidgets.QSlider(self.centralwidget)
        self.strategySlider.setGeometry(QtCore.QRect(310, 210, 160, 19))
        self.strategySlider.setOrientation(QtCore.Qt.Horizontal)
        self.strategySlider.setObjectName("strategySlider")
        self.strategy_count = QtWidgets.QLabel(self.centralwidget)
        self.strategy_count.setGeometry(QtCore.QRect(540, 210, 16, 16))
        self.strategy_count.setObjectName("strategy_count")
        self.count = QtWidgets.QLabel(self.centralwidget)
        self.count.setGeometry(QtCore.QRect(370, 300, 54, 12))
        self.count.setObjectName("count")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 300, 54, 12))
        self.label_3.setObjectName("label_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(490, 210, 41, 16))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 30, 54, 12))
        self.label_4.setObjectName("label_4")
        self.checkBox_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_11.setGeometry(QtCore.QRect(330, 80, 71, 16))
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(260, 120, 481, 61))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(30, 30, 111, 16))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(170, 30, 111, 16))
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(330, 20, 381, 18))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_2.addWidget(self.checkBox_5)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(330, 50, 381, 18))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_6 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_3.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_3.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_3.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_3.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_3.addWidget(self.checkBox_10)
        Lucky.setCentralWidget(self.centralwidget)

        self.retranslateUi(Lucky)
        QtCore.QMetaObject.connectSlotsByName(Lucky)

    def retranslateUi(self, Lucky):
        _translate = QtCore.QCoreApplication.translate
        Lucky.setWindowTitle(_translate("Lucky", "Lucky"))
        item = self.answer_table.horizontalHeaderItem(1)
        item.setText(_translate("Lucky", "开奖号码"))
        self.refresh.setText(_translate("Lucky", "刷新开奖结果"))
        self.statistics.setText(_translate("Lucky", "重新计算"))
        self.label.setText(_translate("Lucky", "计算结果："))
        item = self.result_table.horizontalHeaderItem(0)
        item.setText(_translate("Lucky", "号码"))
        item = self.result_table.horizontalHeaderItem(1)
        item.setText(_translate("Lucky", "权重"))
        item = self.result_table.horizontalHeaderItem(2)
        item.setText(_translate("Lucky", "平均遗漏数"))
        item = self.result_table.horizontalHeaderItem(3)
        item.setText(_translate("Lucky", "当前遗漏数"))
        item = self.result_table.horizontalHeaderItem(4)
        item.setText(_translate("Lucky", "最大遗漏数"))
        self.lucky.setText(_translate("Lucky", "生成数据"))
        self.label_2.setText(_translate("Lucky", "组合数："))
        self.strategy_count.setText(_translate("Lucky", "%"))
        self.count.setText(_translate("Lucky", "条数据"))
        self.label_3.setText(_translate("Lucky", "0"))
        self.label_4.setText(_translate("Lucky", "组合位置："))
        self.checkBox_11.setText(_translate("Lucky", "全部"))
        self.groupBox.setTitle(_translate("Lucky", "遗漏数"))
        self.radioButton.setText(_translate("Lucky", "历史最大遗漏数"))
        self.radioButton_2.setText(_translate("Lucky", "历史平均遗漏数"))
        self.checkBox.setText(_translate("Lucky", "12XXX"))
        self.checkBox_2.setText(_translate("Lucky", "1X3XX"))
        self.checkBox_3.setText(_translate("Lucky", "1XX4X"))
        self.checkBox_4.setText(_translate("Lucky", "1XXX5"))
        self.checkBox_5.setText(_translate("Lucky", "X23XX"))
        self.checkBox_6.setText(_translate("Lucky", "X2X4X"))
        self.checkBox_7.setText(_translate("Lucky", "X2XX5"))
        self.checkBox_8.setText(_translate("Lucky", "XX34X"))
        self.checkBox_9.setText(_translate("Lucky", "XX3X5"))
        self.checkBox_10.setText(_translate("Lucky", "XXX45"))

