# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lucky.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lucky(object):
    def setupUi(self, Lucky):
        Lucky.setObjectName("Lucky")
        Lucky.resize(720, 600)
        Lucky.setMinimumSize(QtCore.QSize(720, 600))
        Lucky.setMaximumSize(QtCore.QSize(720, 600))
        self.centralwidget = QtWidgets.QWidget(Lucky)
        self.centralwidget.setObjectName("centralwidget")
        self.answer_table = QtWidgets.QTableWidget(self.centralwidget)
        self.answer_table.setGeometry(QtCore.QRect(5, 5, 202, 590))
        self.answer_table.setMinimumSize(QtCore.QSize(202, 590))
        self.answer_table.setMaximumSize(QtCore.QSize(202, 590))
        self.answer_table.setObjectName("answer_table")
        self.answer_table.setColumnCount(2)
        self.answer_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("期号")
        item.setBackground(QtGui.QColor(240, 229, 189))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.answer_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.answer_table.setHorizontalHeaderItem(1, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 60, 501, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refresh = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.refresh.setObjectName("refresh")
        self.horizontalLayout.addWidget(self.refresh)
        self.statistics = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.statistics.setObjectName("statistics")
        self.horizontalLayout.addWidget(self.statistics)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 100, 54, 12))
        self.label.setObjectName("label")
        self.result_table = QtWidgets.QTableWidget(self.centralwidget)
        self.result_table.setGeometry(QtCore.QRect(210, 120, 502, 211))
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(5)
        self.result_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(4, item)
        self.lucky = QtWidgets.QPushButton(self.centralwidget)
        self.lucky.setGeometry(QtCore.QRect(220, 350, 481, 23))
        self.lucky.setObjectName("lucky")
        self.result_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.result_edit.setGeometry(QtCore.QRect(210, 390, 501, 201))
        self.result_edit.setObjectName("result_edit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 71, 16))
        self.label_2.setObjectName("label_2")
        self.strategySlider = QtWidgets.QSlider(self.centralwidget)
        self.strategySlider.setGeometry(QtCore.QRect(280, 20, 160, 19))
        self.strategySlider.setOrientation(QtCore.Qt.Horizontal)
        self.strategySlider.setObjectName("strategySlider")
        self.strategy_count = QtWidgets.QLabel(self.centralwidget)
        self.strategy_count.setGeometry(QtCore.QRect(460, 20, 54, 12))
        self.strategy_count.setObjectName("strategy_count")
        self.count = QtWidgets.QLabel(self.centralwidget)
        self.count.setGeometry(QtCore.QRect(330, 100, 54, 12))
        self.count.setObjectName("count")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 100, 54, 12))
        self.label_3.setObjectName("label_3")
        Lucky.setCentralWidget(self.centralwidget)

        self.retranslateUi(Lucky)
        QtCore.QMetaObject.connectSlotsByName(Lucky)

    def retranslateUi(self, Lucky):
        _translate = QtCore.QCoreApplication.translate
        Lucky.setWindowTitle(_translate("Lucky", "Lucky"))
        item = self.answer_table.horizontalHeaderItem(1)
        item.setText(_translate("Lucky", "开奖号码"))
        self.refresh.setText(_translate("Lucky", "刷新开奖结果"))
        self.statistics.setText(_translate("Lucky", "重新计算"))
        self.label.setText(_translate("Lucky", "计算结果："))
        item = self.result_table.horizontalHeaderItem(0)
        item.setText(_translate("Lucky", "号码"))
        item = self.result_table.horizontalHeaderItem(1)
        item.setText(_translate("Lucky", "权重"))
        item = self.result_table.horizontalHeaderItem(2)
        item.setText(_translate("Lucky", "历史遗漏数"))
        item = self.result_table.horizontalHeaderItem(3)
        item.setText(_translate("Lucky", "当前遗漏数"))
        item = self.result_table.horizontalHeaderItem(4)
        item.setText(_translate("Lucky", "最大遗漏数"))
        self.lucky.setText(_translate("Lucky", "生成数据"))
        self.label_2.setText(_translate("Lucky", "组合数："))
        self.strategy_count.setText(_translate("Lucky", "0%"))
        self.count.setText(_translate("Lucky", "条数据"))
        self.label_3.setText(_translate("Lucky", "0"))

